
                  <?php
                  if(isset($_GET['quanly'])){
                    $tam = $_GET['quanly'];
                  }else{
                    $tam = '';
                  }
                  if($tam=='danhmucsanpham'){
                    include("banner2.php");
                    include("main/danhmuc.php");
                  }elseif($tam=='giohang'){
                    include("banner2.php");
                    include("banner3.php");
                    include("main/giohang.php");
                  }elseif($tam=='tintuc'){
                    include("banner2.php");
                    include("main/tintuc.php");
                  }elseif($tam=='lienhe'){
                    include("banner2.php");
                    include("banner3.php");
                    include("main/lienhe.php");
                  }elseif($tam=='sanpham'){
                    include("banner2.php");
                    include("main/sanpham.php");	
                  }elseif($tam=='dangky'){
                    include("banner2.php");
                    include("main/dangky.php");
                  }elseif($tam=='thanhtoan'){
                    include("banner2.php");
                    include("banner3.php");
                    include("main/thanhtoan.php");
                  }elseif($tam=='dangnhap'){
                    include("banner2.php");
                    include("main/dangnhap.php");
                  }elseif($tam=='timkiem'){
                    include("banner2.php");
                    include("main/timkiem.php");
                  }elseif($tam=='camon'){
                    include("banner2.php");
                    include("banner3.php");
                    include("main/camon.php");
                  }elseif($tam=='thaydoimatkhau'){
                    include("banner2.php");
                    include("main/thaydoimatkhau.php");
                  }elseif($tam=='nguoidung'){
                    include("banner2.php");
                    include("main/nguoidung.php");
                  }elseif($tam=='suanguoidung'){
                    include("banner2.php");
                    include("main/sua_nguoidung.php");
                  }else{
                    include("banner.php");
                    include("banner3.php");
                    include("main/index.php");
                  }
                  ?>